title: Menstrudel | Private & Offline Period Tracker
description: "A free, open-source, and completely offline period tracker app that puts your privacy first. No ads, no sign-ups, and no cloud."
url: "https://menstrudel.app"
logo: /icon/Menstrudel_cropped.png 
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap 

social:
  name: Menstrudel
  links:
    - https://github.com/J-shw/Menstrudel