name: Auto Increment Build Number

on:
  push:
    branches:
      - main

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get current version
        id: get_version
        run: |

            VERSION_LINE=$(grep "version:" pubspec.yaml)
            echo "Current version line: $VERSION_LINE"

            BASE_VERSION=$(echo "$VERSION_LINE" | sed -E 's/version: ([0-9]+\.[0-9]+\.[0-9]+)\+([0-9]+)/\1/')
            echo "Base version: $BASE_VERSION"

            BUILD_NUMBER=$(echo "$VERSION_LINE" | sed -E 's/version: [0-9]+\.[0-9]+\.[0-9]+\+([0-9]+)/\1/')
            echo "Current build number: $BUILD_NUMBER"

            NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
            echo "New build number: $NEW_BUILD_NUMBER"

            echo "base_version=$BASE_VERSION" >> "$GITHUB_OUTPUT"
            echo "new_build_number=$NEW_BUILD_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Update pubspec.yaml
        run: |

            sed -i -E "s/version: [0-9]+\.[0-9]+\.[0-9]+\+[0-9]+/version: ${{ steps.get_version.outputs.base_version }}+${{ steps.get_version.outputs.new_build_number }}/" pubspec.yaml
            echo "Updated pubspec.yaml:"
            cat pubspec.yaml

      - name: Commit and Push new version
        run: |

            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git diff --quiet pubspec.yaml || git commit -am "chore(version): Auto-increment build number to ${{ steps.get_version.outputs.new_build_number }}"

            if [ $(git status --porcelain | wc -l) -gt 0 ]; then
                git push
            else
                echo "No changes to commit or push."
            fi